### PR TITLE
Values with and without  `cf_sql_` prefix must be equivalent

### PR DESCRIPTION
**Pull request by shaedrich**

### CODE REVIEW

**Comment by pfreitag** [comment]
Hmm -- I know they are equivalent but I'd like to keep those in there for the sake of IDE's that use it for autocompletion.

**Comment by shaedrich** [comment]
So seen from this angle we should add all values present with `cf_sql_` prefix now additionally without for consistency, shouldn't we?

**Comment by pfreitag** [comment]
Yeah probably should.

**Comment by shaedrich** [comment]
Okay, I'll change that.

**Comment by pfreitag** [comment]
@shaedrich FYI CF2016 Failure: cfqueryparam.json was NOT valid JSON

**Comment by shaedrich** [comment]
Done.

**Pull request merged**
