### PR TITLE
Add structToSorted function

### PR DESCRIPTION
**Pull request by aliaspooryorik**
Addresses: https://github.com/foundeo/cfdocs/issues/774

Think I've added it correctly to the listing .json files.

### CODE REVIEW

**Comment by KamasamaK** [comment]
1. The names of the params should be consistent where possible. Right now, the first parameter is named `struct` and `anyStruct` in the `syntax` and `structure` in the `params` array.

1. `UDF` is not one of the [valid param types](https://github.com/foundeo/cfdocs/blob/master/data/cfdocs.schema.json#L99). Use `function`.

1. You can add a [`callback_params`](https://github.com/foundeo/cfdocs/blob/master/data/cfdocs.schema.json#L146) array within the callback's `params` entry to describe its params. Unfortunately, the cfdocs.org site does not yet read that, so it would be premature to remove it from `description`.

1. I see you added `structsetmetadata` to `data/en/struct-functions.json` but it appears to be missing from `data/en/all.json`. I'm not sure how that got through, but since you're modifying that file anyway, I figure you could add it.

**Comment by aliaspooryorik** [comment]
@KamasamaK Thanks for feedback.

1. updated them all to `structure`
2. I copied the structeach.json file as my starting template and that used `UDF` so I've updated that config to `function` as well as the structtosorted.json.
3. Not quite sure what you mean here - do you have an example?
4. `structsetmetadata` added to all.json as requested

**Comment by KamasamaK** [comment]
Regarding 3, I don't think there are any examples yet in the JSON data, but [here is the closest I have to an example](https://github.com/foundeo/cfdocs/issues/525#issuecomment-327285363). Just know that schematically, `callback_params` and `params` are the same. This would basically be what you put into the param `description` transposed to `callback_params`:

```json
"callback_params": [
	{
			"name": "value1",
			"description": "Value of the key/value pair in the struct",
			"required": true,
			"default": "",
			"type": "any",
			"values": []
	},
	{
			"name": "value2",
			"description": "Value of the key/value pair to compare against",
			"required": true,
			"default": "",
			"type": "any",
			"values": []
	},
	{
			"name": "key1",
			"description": "Key name of the key/value pair in the struct",
			"required": true,
			"default": "",
			"type": "string",
			"values": []
	},
	{
			"name": "key2",
			"description": "Key name of the key/value pair to compare against",
			"required": true,
			"default": "",
			"type": "string",
			"values": []
	}
]
```

**Comment by KamasamaK** [comment]
Since JSON schema validation is case-sensitive, make sure the [data types match exactly](https://github.com/foundeo/cfdocs/blob/35c75c11113d5eb25494ce8542c1c4649544db38/data/cfdocs.schema.json#L99). e.g. `Any` vs. `any`. Looks good otherwise.

@pfreitag What are your thoughts on including HTML in the data? e.g. `<strong>`

**Comment by aliaspooryorik** [comment]
Have updated to `any`. I got the `Any` case from the linked example: https://github.com/foundeo/cfdocs/issues/525#issuecomment-327285363

As for HTML in the data - I got that from StructEach doc which I used as a template: 
https://github.com/foundeo/cfdocs/blob/master/data/en/structeach.json#L11

**Comment by pfreitag** [comment]
@KamasamaK - I don't want HTML in the JSON.

The site currently supports back ticks in most places which causes the text to be wrapped in a `<code>` tag. 

If we really need strong then I'd favor using `*something bold*` as the syntax instead of HTML. I'd welcome your opinion as you are a plugin developer using this repository - thoughts?

**Comment by pfreitag** [comment]
@aliaspooryorik thanks for your contributions here, I'm going to merge this PR - we can remove the HTML in another PR (I know you didn't add it in this one you were just updating what was there).

**Comment by KamasamaK** [comment]
For the usage here, I agree that backticks would be a better alternative. Incidentally, the platform I work on uses a subset of markdown, so the backticks work well there. I've created #883 for further discussion.

**Pull request merged**
