### PR TITLE
Changes to Elvis Operator and one more.

### PR DESCRIPTION
**Pull request by alorne**
I changed the isInteger (this does not exist in cf) in the examples to isNumeric. The examples are runnable now. I also added an if/elseif/else example. Lastly, I hid the `.vscode` folder, hope that's ok. Cheers!

### CODE REVIEW

**Comment by shaedrich** [comment]
You could add a note to your new example like: "It's not advisable to nest it, though, because of poor readability.".

**Comment by alorne** [comment]
I didn't think about that. I had a need for it in a project I am working on right now and it worked well. I will remove the commit since it is not preferred.

**Comment by shaedrich** [comment]
Well, I guess, it's nice to now in general and helpful in rare cases like yours.

**Comment by alorne** [comment]
Ok, added the note to the example

**Comment by pfreitag** [comment]
Excellent changes - thanks @alorne

**Comment by alorne** [comment]
Glad to help!

**Pull request merged**
