### PR TITLE
Update valuelist.json

### PR DESCRIPTION
**Pull request by shaedrich**
Better description and added missing example

### CODE REVIEW

**Comment by pfreitag** [comment]
Hi @shaedrich thanks for the Pull Request!

It looks like the integration test failed because your update was not valid JSON (you have an extra comma at the end of your examples. Would you be able to update and resubmit?

**Comment by shaedrich** [comment]
I fixed this but there is still an error...

**Comment by pfreitag** [comment]
Thanks - it is still failing the integration text because you have the result set to a value that is not the actual result of running the code - I will take care of that, thanks for contributing!

**Comment by shaedrich** [comment]
Okay, thank you.

**Pull request merged**
