### PR TITLE
Create canonicalize.json

### PR DESCRIPTION
**Pull request by yogidevbear**

### CODE REVIEW

**Comment by pfreitag** [comment]
Hi -- thanks for the pull, however it failed the integration tests: https://travis-ci.org/foundeo/cfdocs/builds/91601554#L153 invalid json.

**Comment by yogidevbear** [comment]
Hi Pete. Just trying to figure out my issue with the Travis CI stuff. I'm under the assumption that I added `canonicalize` to index.json and functions.json, but not in the same branch so to speak which is why I'm seeing the errors in https://travis-ci.org/foundeo/cfdocs/builds/91605233

**Comment by yogidevbear** [comment]
I think the last errors in Travis CI should resolve now (I hope).

**Comment by yogidevbear** [comment]
So one of the errors is https://travis-ci.org/foundeo/cfdocs/builds/91605233#L306, but canonicalize is not a tag function. It appears to be cfscript-only.

**Comment by yogidevbear** [comment]
Error between keyboard and chair :smile: 
I had the wrong type set to tag instead of function

**Comment by pfreitag** [comment]
Ok I will take a look shortly - I'm out of the office right now -- I think the issue is probably that lucee (which is what Travis is running) may not support the function?

**Comment by pfreitag** [comment]
Oh I see test passes now nice job!!

**Pull request merged**
