### PR TITLE
Update arrayfind.json

### PR DESCRIPTION
**Pull request by bradmarshall**
Updated the description of using arrayFind with a closure / callback function. Previously, it was unclear what arrayFind() would return in the event that an array contains the item being searched for more than once. Updated to indicate that the index returned is the index of the FIRST found item in the array.

### CODE REVIEW

**Comment by shaedrich** [comment]
Good job :+1: Then you could reference to reference to `arrayFindAll()` as well.

**Comment by bradmarshall** [comment]
Great idea! Updated to include link to arrayFindAll. It seems like links get auto-parsed which is awesome but I'm new around here so let me know if I did that wrong.

**Comment by shaedrich** [comment]
Everything is well so don't worry :)

Yeah, @pfreitag did a great job :+1:

**Comment by bradmarshall** [comment]
Awesome! Agreed!

**Comment by pfreitag** [comment]
Thanks @bradmarshall 

Congrats on your first contribution to cfdocs!

**Pull request merged**
