### PR TITLE
[CLEANUP] Speed up type tests

### LINKED ISSUE #593: Only test if type matches
Only files with the type used inside one of the tests should be passed in so we just need to loop over them without having to filter any unwanted files to filter with a conditional inside [TestIndexes](/foundeo/cfdocs/tree/master/tests/tests/TestIndexes.cfc).

https://github.com/foundeo/cfdocs/blob/a18feb8dc8a751d3210196812b67cd22dc664856/tests/tests/TestIndexes.cfc#L39-L41

### PR DESCRIPTION
**Pull request by shaedrich**
Resolve #593: Only test if type matches

### CODE REVIEW

**Comment by pfreitag** [comment]
I don't think this change will speed up the tests... there will be more `fileRead` operations.

**Comment by shaedrich** [comment]
It will prevent the test to loop over files which do not match the type needed.

**Comment by pfreitag** [comment]
Let's assume that there are 500 files, 200 tags, 300 functions. With this code you would do 500 fileReads, then 200 fileReads, then 500 fileReads then 300 fileReads for a total of 1500. The code as it was would only do 1000.

**Comment by shaedrich** [comment]
Well, I removed some duplicated parts.

But did you understand my intention? Maybe you know how to combine it with the origin file to improve it...

**Comment by pfreitag** [comment]
Yeah I understood your intention... maybe something like this:
```
types = {tags=[], functions=[], listings=[]};
for (filePath in files) {
		json = fileRead(filePath);
		isItJson = isJSON(json);
		fileName = getFileFromPath(filePath);
		if (isItJson) {
			json = deserializeJSON(json);
			if (structKeyExists(json, "type")) {
				if (json.type IS "tag") {
					arrayAppend(fileTypes.tags, json.name);
				} else if (json.type IS "function") {
					arrayAppend(fileTypes.functions, json.name);
				} else if (json.type IS "listing") {
					arrayAppend(fileTypes.listings, json.name);
				}
			}
		}
}
```

Then you can just go through the types.tags array, etc. instead of reading the file each time.

**Comment by shaedrich** [comment]
That would be even better. I thought too complicated.

**Comment by shaedrich** [comment]
By the way: Sorry for causing inconvenience and time-consuming discussions...

**Comment by shaedrich** [comment]
(!)JSON Index Tests
       (+)should be in index.json if it is a tag or a function (1605 ms)
       (+)should be in tags.json if it is a tag (31 ms)
       (!)should be in functions.json if it is a function (23 ms)
	      -> Failure: yesNoFormat was not in functions.json index

Now we are getting closer to the point.

**Comment by shaedrich** [comment]
Do we really need to check if it `isJSON` because we already to it in [TestDataFormat](/foundeo/cfdocs/tree/master/tests/tests/TestDataFormat.cfc)?

**Comment by shaedrich** [comment]
@pfreitag Do we really need to check if it `isJSON` because we already to it in [TestDataFormat](/foundeo/cfdocs/tree/master/tests/tests/TestDataFormat.cfc)?

**Comment by shaedrich** [comment]
@pfreitag Are you still with me?

**Comment by shaedrich** [comment]
After all: It works!

**Comment by shaedrich** [comment]
@pfreitag Could you just react to some issues in between?

**Pull request merged**
