### PR TITLE
lucee parallel functions

### PR DESCRIPTION
**Pull request by jordanclark**
struct, array & query cleanup & standardize map(), reduce(), filter(), each(), some()
- add missing "parallel" and "maxThreads" arguments
- converted "closure" to function with callback_params

### CODE REVIEW

**Comment by pfreitag** [comment]
Hi @jordanclark 

Thanks for this PR, though I don't think I can merge this with multiple syntaxes, we had discussed coming up with a way to show multiple syntaxes a while back - I think @shaedrich might have started investigating coming up with a syntax in the json to support it.

What you could do is keep syntax as is for now, and I can merge the arguments docs at least for now.

**Comment by jordanclark** [comment]
Hi @pfreitag 

I'm not sure I understand the issue that it can't have multiple syntaxes? I'm guessing you mean that it includes lucee only arguments?

The thing is, I've just taken what already exists on cfdocs and standardized it for these tags, if you take a look at https://cfdocs.org/arrayeach you'll see it already has ```[, parallel] & [, maxthreads]```

But then https://cfdocs.org/arrayfilter does not, even though they are similar, so I made them consistent.

My thought was since the arguments are documented as lucee 4.5+ only it would be ok?
If not, what about syntax like ```[(lucee), parallel] [(lucee), maxThreads]```

If not let me know and I can take them out, but I also added the callback functions params to the syntax which I think is useful so I'd still like to keep that at least.

**Comment by pfreitag** [comment]
Hi @jordanclark sorry I think I misread something when reviewing it previously.

**Comment by KamasamaK** [comment]
@jordanclark Please keep in mind that changing the param names should comply with #898. For example, in `arrayEach` you changed `callback` to `function` which is not the name ACF 2018+ expects but is an acceptable alias in Lucee.

**Comment by jordanclark** [comment]
@KamasamaK Sorry I didn't realize ACF had a different param name, I'll correct in another pull request

**Pull request merged**
