### PR TITLE
Fix and improve callback_params output

### PR DESCRIPTION
**Pull request by shaedrich**

### CODE REVIEW

**Comment by pfreitag** [comment]
Just want to make sure this one is tested since it is a view change, please confirm - thanks!

**Comment by pfreitag** [comment]
Sorry closed it by accident when I commented.

**Comment by pfreitag** [comment]
Hmm looking at this the only difference I see is that it switched the h4 to strong? Was this done in another PR if so can we close this one?

**Comment by shaedrich** [comment]
Yupp, that's all

**Comment by shaedrich** [comment]
Thanks!

**Pull request merged**
