### PR TITLE
Makes externallist an actual array

### PR DESCRIPTION
**Pull request by ianosullivan**
Makes externallist an actual array (not a string) so the code will work when run in the engine.

### CODE REVIEW

**Comment by shaedrich** [comment]
Why should a list for a list function be an array?

**Comment by ianosullivan** [comment]
Perhaps I was a bit hasty. I ran the code and saw this error when I ran the code - http://take.ms/VP5AT - and thought is was meant to be an array.

**Comment by shaedrich** [comment]
For some reason the right member function is `str.listAppend()`.

**Comment by ianosullivan** [comment]
Yep list member functions have 'list' as a prefix as per here - [https://cfdocs.org/member](https://cfdocs.org/member) so perhaps that line should be fixed instead.

**Comment by shaedrich** [comment]
I added the member syntax to `listAppend()` in #972. Feel free to make a pull request to fix the example of `listMap()`.

**Pull request closed without merging**
