### PR TITLE
Added example to StructUpdate

### PR DESCRIPTION
**Pull request by shaedrich**

### CODE REVIEW

**Comment by pfreitag** [comment]
@shaedrich - the json is invalid for this example... FYI you can use this to make the JSON: https://cfdocs.org/utilities/json/

**Comment by shaedrich** [comment]
@pfreitag Oh thanks, I did not know that (Y)

**Comment by pfreitag** [comment]
@shaedrich Thanks for fixing and thanks again for your contribution, merged.

**Comment by shaedrich** [comment]
@pfreitag You're welcome and sorry for my lack of concentration sometimes which require needless commits and demand your attention multiple times.

**Comment by pfreitag** [comment]
@shaedrich No problem at all, your willingness to contribute far outweighs any minor issues

**Comment by shaedrich** [comment]
@pfreitag Thanks a lot for that compliment

**Pull request merged**
