### PR TITLE
Rename E function params

### PR DESCRIPTION
**Pull request by shawnoden**
2nd batch of function params for E functions.

### CODE REVIEW

**Comment by shaedrich** [comment]
It's hard to guess your actual changes because there's so much changed which doesn't seem to correspond with your pr's title.

**Comment by shawnoden** [comment]
Hmmm... there should have only been about 6 or so files changed, all in the 2nd half of the "E" functions. Did my PR get borked up somehow? I'll look at it.

**Comment by pfreitag** [comment]
@shawnoden Can you re-create the PR with just the 6 files you changed? 

Looks like you might need to `rebase` your branch to synchronize. When you fork a repo, it gets out of date or behind this one, you probably forked it a long time ago and you just need to resync it. 

Easy way to do it is to just back a backup of your changes and then delete your fork, and fork it again, but if you want to spend some time on the _proper_ way to do it checkout the **Update** section here: http://adamtuttle.codes/blog/2014/your-first-github-pull-request/

**Comment by shawnoden** [comment]
@pfreitag Will do. Sorry about that. I forked the entire code base a long time ago. The branch for these changes is more recent, but still a few weeks old. I thought I rebased before I sent the PR, but apparently not. I'll get it fixed and resubmitted.

**Comment by shawnoden** [comment]
Just close this PR. I resubmitted each of the 4 functions that changed. This should complete E functions, except for the `entity...()` functions. I'll tackle those separately.

**Pull request closed without merging**
