### PR TITLE
Update serializeJson.json

### PR DESCRIPTION
**Pull request by evagoras**
Added examples of wrong serializations for ACF11.

### CODE REVIEW

**Comment by evagoras** [comment]
At the same time I was adding this, Mingo Hagen opened a warning in the notes:
https://github.com/foundeo/cfdocs/issues/280

I suppose you can discard this PR if you think the note is a better option.

**Comment by evagoras** [comment]
Edited and pushed. Cheers!

**Comment by pfreitag** [comment]
Excellent thanks @evagoras !!

**Comment by pfreitag** [comment]
fixes #280

**Pull request merged**
