### PR TITLE
Create onServerStart.json

### PR DESCRIPTION
**Pull request by ianosullivan**
Adding page details for onServerStart

### CODE REVIEW

**Comment by pfreitag** [comment]
Thanks -- this is not supported on Lucee correct? If not then we need to remove "lucee" from the engines key to indicate that it is not supported.

**Comment by ianosullivan** [comment]
Pete,
I believe you are correct. I've removed the Lucee reference. I can't find a reference to it anywhere. I can't check the Admin though to be 100% as we don't have it installed anywhere at the moment.
Ian.

**Comment by pfreitag** [comment]
I don't see anything in the admin, thanks for adding this - I'll merge it in.

**Comment by ianosullivan** [comment]
Cool, happy to help

**Pull request merged**
