### PR TITLE
Make description consistent to consistent to `transactionRollback()`'…

### PR DESCRIPTION
**Pull request by shaedrich**
…s `savepoint' param

### CODE REVIEW

**Comment by pfreitag** [comment]
Thanks I tried updating the commit on that previous PR with your suggestion, but it didn't take.

**Comment by shaedrich** [comment]
Oh, okay. Did you see an error message or like? Maybe only @michaelborn was allowed to…

Did you reported it via github's feature feedback functionality?

**Comment by pfreitag** [comment]
Yes I think it said I didn't have permission, but I was able to edit other PR commits, just not the suggestion you did.

**Comment by shaedrich** [comment]
Hmmm…Maybe it was a little too short-sighted. But you can report the case you had if you want to: https://www.research.net/r/SuggestedChanges

**Pull request merged**
