### PR TITLE
Initial schema changes for new member_details

### PR DESCRIPTION
**Pull request by KamasamaK**
As discussed in #525, here are the proposed changes. I would still be interested in feedback from @pfreitag  regarding my latest comments in that issue.

### CODE REVIEW

**Comment by pfreitag** [comment]
@KamasamaK - I can think of one case where the first argument is not the object being operated on... `find` and `reFind`

**Comment by pfreitag** [comment]
Otherwise it looks good... maybe we just have to have a index variable that tells which param it operates on (defaulted to first, 1) so we could still avoid duplicating params.

**Comment by KamasamaK** [comment]
Ok, I added a property for the index.

**Comment by pfreitag** [comment]
Thanks for your work on this @KamasamaK

**Pull request merged**
