### PR TITLE
Lucee function hash40() - Minor corrections.

### PR DESCRIPTION
**Pull request by shawnoden**
Added the discouraged flag since this function is marked as only useful for backwards compat. Also changed some simple text issues.

### CODE REVIEW

**Comment by pfreitag** [comment]
Hi @shawnoden looks like there is a merge conflict here, can you fix that?

**Comment by shawnoden** [comment]
Fixed.

**Comment by shawnoden** [comment]
@pfreitag Is anything else needed on this PR?

**Comment by shawnoden** [comment]
Ahh, it looks like this change was merged from #1261 .  This can be closed.

**Pull request closed without merging**
