### PR TITLE
Contains operator

### PR DESCRIPTION
**Pull request by aliaspooryorik**
Added `contains` operator

### CODE REVIEW

**Comment by pfreitag** [comment]
There is also `does not contain` (the negation of `contains`)

@KamasamaK is there a lucee shorthand operator for that as well?

@aliaspooryorik let me know if you want to update your PR with these suggested additions or just merge this one as is

**Comment by KamasamaK** [comment]
@pfreitag Yes, the shorthand for that is `NCT `.

**Comment by aliaspooryorik** [comment]
@pfreitag might as merge as is - I will do the other suggestions when I get a chance. If you'd rather wait and do in one go that's fine :)

**Comment by pfreitag** [comment]
Merged it now ;-) Thanks @aliaspooryorik

**Pull request merged**
