### PR TITLE
Adding reference to onServerStart function

### PR DESCRIPTION
**Pull request by ianosullivan**
onServerStart page needs to be created though

### CODE REVIEW

**Comment by pfreitag** [comment]
Thanks -- let's create the page first and then I'll merge this PR, otherwise it will just result in a 404

**Comment by ianosullivan** [comment]
Can do Pete. So I just create the new file here and send a pull request is it? Not overly familiar with the process. 
Ian

**Comment by pfreitag** [comment]
Yes that is correct I would just copy onRequestStart.json and modify it accordingly.

You can send it in a separate pull request

**Comment by pfreitag** [comment]
Thanks again!

**Pull request merged**
