### PR TITLE
Better example

### PR DESCRIPTION
**Pull request by tomchiverton**
render() doesn't return the output, it outputs there and then. Also the previous example didn't match the "expected" anyway.

### CODE REVIEW

**Comment by pfreitag** [comment]
Hi @tomchiverton  - thanks for the PR. Travis CI is telling us that the JSON is not valid, can you check on that and update it?

**Comment by KamasamaK** [comment]
The issue is that the double quotes are no longer being escaped.

**Comment by jordanclark** [comment]
I fixed the json in @tomchiverton's pull request, sorry I didn't know how to post the change here.
https://github.com/foundeo/cfdocs/pull/1132

**Comment by tomchiverton** [comment]
Ta. I can't find anyway to close this PR

**Pull request closed without merging**
