### PR TITLE
Remove optional parameters from tag syntax

### PR DESCRIPTION
**Pull request by shaedrich**
The whole signature broke the layout

### CODE REVIEW

**Comment by pfreitag** [comment]
@shaedrich Maybe we should keep `value` in there because while not required all the time it is used most of the time. What do you think?

**Comment by shaedrich** [comment]
I see your point, but that would break ranks, won't it?

**Comment by pfreitag** [comment]
I think the tag syntax should mainly be useful, I don't think I've had a strict rule to apply as to what is included there. Is it usually just the required attribute that are shown?

**Comment by shaedrich** [comment]
What's a cookie without a `value`?

Maybe we could make a second signature underneath the first one?

**Comment by pfreitag** [comment]
I think the only reason that you can or would omit `value` is if you also have `expires="now"`

**Comment by shaedrich** [comment]
But then set an infinite cookie without a value? So just checking it for existence?

**Comment by pfreitag** [comment]
Merging this, looks like you can also set a cookie without a value, not sure why you would want to do this but its possible.

**Pull request merged**
