### PR TITLE
Added Examples/Description for ToNumeric

### PR DESCRIPTION
**Pull request by Xcreen**
- Added Description
- Added Default and Values for Radix
- Added two Examples (String/Hex/Bin Cast)

### CODE REVIEW

**Comment by shaedrich** [comment]
Value "2-36" for `Radix` argument looks like one string but is a range of numbers. That might be confusing....

**Comment by Xcreen** [comment]
Mhhh thats correct, but have you any suggest?    
Writing every number, also makes no sense...

**Comment by shaedrich** [comment]
That does not make sense either, you're right. What about `"2","...","36"`?

**Comment by Xcreen** [comment]
Mhh you mean: `"2 ... 36"`  ?
Because `"2","...","36"` look also weird due the line-break, than i look like "..." is a own value.

**Comment by shaedrich** [comment]
I used "..." when I wanted to indicate "and so on" so anything after "..." then is to limit that range.

"..." in a single line looks a bit weird but more clear to me because every value has it's own line.

**Comment by pfreitag** [comment]
Thanks @Xcreen

**Pull request merged**
