### PR TITLE
Markdown parser

### PR DESCRIPTION
**Pull request by shaedrich**
- #616 
- #618 
- #620

### CODE REVIEW

**Comment by pfreitag** [comment]
I'm going to decline this PR, right now we support backticks in the autoLink function, I don't want to support full markdown in these areas, I think it will complicate things in the long run.

Thanks for the effort in building this, and all the work you have done thus far!

**Comment by shaedrich** [comment]
So something went's wrong in `autoLink`. In the referenced pr we found out, that backticks do not work in that case. Do you have any idea, why this happens?

**Comment by shaedrich** [comment]
Resolved with 32bf369af7a4b08a9ce8065aa53822a038e6d976.

**Comment by shaedrich** [comment]
Resolved with 32bf369af7a4b08a9ce8065aa53822a038e6d976.

**Pull request closed without merging**
