### PR TITLE
Added example for cf-2018 cfscript tag changes

### PR DESCRIPTION
**Pull request by saravanakumar404**

### CODE REVIEW

**Comment by KamasamaK** [comment]
This contains the same change as #1297 because that change was made on `master` from which this branched.

**Comment by saravanakumar404** [comment]
> This contains the same change as #1297 because that change was made on `master` from which this branched.

@Kamasamak pull request #1297 don't having cfscript.json file changes. I'm not sure why the pull request #1297 not merged😥

**Comment by KamasamaK** [comment]
@saravanakumar404 I know, that's why I said this has the change from that PR, not vice versa. That's why all changes should be made on a separate branch from `master`.

**Comment by pfreitag** [comment]
Ok, I just merged this one, I will close the other PR.

**Pull request merged**
