### PR TITLE
Fix link to ArrayFindAll

### PR DESCRIPTION
**Pull request by ryandeba**
Link was pointing to "/ArrayFindAt" which doesn't exist. I suspect that was meant to be "/ArrayFindAll"

### CODE REVIEW

**Comment by pfreitag** [comment]
Thanks I think so, pinging @fmdano as he wrote the guide. Dan can you double check this?

**Comment by fmdano** [comment]
seems like I missed most of the email chain on this...did I not update a link right in the arrayFindall? If there is an issue in the file, just change it...is that what someone wants to do? 
dan

Date: Thu, 25 Feb 2016 12:51:50 -0800

**Comment by pfreitag** [comment]
@fmdano - in your http://cfdocs.org/closures guide there was a mention of an `ArrayFindAt` function (which is not documented by Adobe) in the list of closure functions, @ryandeba changed it to `ArrayFindAll` thinking that was what you had meant.

I just wanted to ping you to make sure we weren't removing a reference to some undocumented function.

**Comment by fmdano** [comment]
Ah I see, no that was a typo...darnit guess i was typing too fast or adding typos to see if others would catch them...LOLglad he caught it...
thanks for letting me know about that.dan

Date: Fri, 26 Feb 2016 07:13:07 -0800

**Pull request merged**
