### PR TITLE
Add function StructSetMetaData

### PR DESCRIPTION
**Pull request by Xcreen**
Add function StructSetMetaData  
Issue: #782 and #604

### CODE REVIEW

**Comment by pfreitag** [comment]
Great work thanks!

**Comment by KamasamaK** [comment]
The ColdFusion version should match their version number, which per #571 would be `2016.0.2`

**Comment by pfreitag** [comment]
Good catch @KamasamaK - since I already merged this one, I just went ahead and fixed the version number myself... commit 80fa024

**Comment by shaedrich** [comment]
@Xcreen Just a small advice: If you write ["fix(es)" or "resolve(s)"](https://help.github.com/articles/closing-issues-using-keywords/) the corresponding will be closed when this pull request ist closed ;-)

**Comment by Xcreen** [comment]
@shaedrich Thanks for the hint. I wasnt sure, if it closes directly.

**Comment by shaedrich** [comment]
It does. I think, that's a pretty handy feature.

**Pull request merged**
