### PR TITLE
Update queryappend.json

### PR DESCRIPTION
**Pull request by scallahanCybernet**
Added support for Lucee 6.0.0.15

### CODE REVIEW

**Comment by scallahanCybernet** [comment]
@pfreitag You may want to update the Lucee version regex in the JSON validator to allow for micro versioning. This didn't pass JSON validation when I entered `6.0.0.15`, but that is the official version this function was added to Lucee.

**Comment by pfreitag** [comment]
yeah, I think we were hoping to support semver style versions there. Could you add in the notes of the engine key the exact version?

**Comment by pfreitag** [comment]
going to merge this since the number of people running a version of 6.0.0 less than 6.0.0.15 has to be close to zero, but feel free to add the note in another PR

**Comment by scallahanCybernet** [comment]
> going to merge this since the number of people running a version of 6.0.0 less than 6.0.0.15 has to be close to zero, but feel free to add the note in another PR

Unless Brad is still messing around with testing something 😝

**Pull request merged**
