### PR TITLE
Added descriptions to arguments lsdayofweek

### PR DESCRIPTION
**Pull request by Miguel-F**
Added descriptions to arguments from the Lucee documentation located here - https://docs.lucee.org/reference/functions/lsdayofweek.html

NOTE: I added some HTML tabs within the description. I am assuming that will work.  If not then just reject this change and I will modify.

### CODE REVIEW

**Comment by shaedrich** [comment]
Do you want to achieve a line break by using `<p />`? It's easier to use `\n` than wrapping it in a tab.

I'm not sure, but I guess, param descriptions are not parsed so this might not work.

**Comment by Miguel-F** [comment]
Thanks for the feedback.  I wasn't really sure what was allowed there.  I was also trying to create a bulleted list.  Is there any option for that?

**Comment by shaedrich** [comment]
People use either "*" or "-" and delimit them using `\n`

In general this could be interesting to read:
* https://github.com/foundeo/cfdocs/issues/883

Somewhere we had a discussion about either to use "*" or "-" but I can't find it right now.

**Comment by Miguel-F** [comment]
I removed the HTML tags and replaced them with `\n` to avoid any potential issues.

**Comment by pfreitag** [comment]
Thanks for contributing and fixing @Miguel-F and thanks for reviewing @shaedrich

**Comment by shaedrich** [comment]
My pleasure, @pfreitag!

**Pull request merged**
