### PR TITLE
cfwebsocket addition, updates to network protocols and enhancement to findCategory function

### PR DESCRIPTION
**Pull request by GiancarloGomez**
Added cfwebsocket.json with basic info, code examples and helpful links.

Updated how findCategory looped thru the categories so it would look at
tags and functions last, which gives it the ability to find a tag or
function in any of the other categories first.

Updates to tags inside network protocol

### CODE REVIEW

**Comment by pfreitag** [comment]
Nice work thanks!

**Comment by pfreitag** [comment]
Thanks! there was a minor json error but I took care of it

**Comment by GiancarloGomez** [comment]
Thanks Pete. For some reason on the site I don't see the breadcrumbs picking up the reference to network protocol tag. Instead it says All CFML tags. The update to findCategory should have fixed that.

**Comment by pfreitag** [comment]
Yes - I had noticed that, thanks for fixing it!

**Comment by GiancarloGomez** [comment]
My pleasure Pete, although I do not see the change reflected on the production site, do you have caching enabled? I did merge your master back into mine to see if it was something there but it still shoes fine on my local copy. 

Have a Merry Christmas!

**Comment by pfreitag** [comment]
Merry Christmas Giancarlo!

The cfdocs.org site is cached by Amazon CloudFront so the changes may take up to 24 hours to show up. But in this case the change you made might have also been due to having an application level cache of the categories in play. 

I'll make sure everything is flushed.

**Comment by pfreitag** [comment]
BTW the `subscribeTo` attribute of `cfwebsocket` mentions the `Application.cfc` settings, it looks like they are not documented yet - would you be willing to add them when you have a chance?

https://github.com/foundeo/cfdocs/edit/master/data/en/application-cfc.json

**Comment by GiancarloGomez** [comment]
Will do Pete!

Thank you,
Giancarlo Gomez
http://giancarlogomez.com

**Comment by GiancarloGomez** [comment]
Hey Pete, 

Just pushed a merge request but I see that it also contains my merges from when I updated my master from yours, if I did this wrong let me know and I will redo.

Thank you,
Giancarlo Gomez
http://giancarlogomez.com

**Pull request merged**
