### PR TITLE
 change param "function" to "callback" for ACF compatibility

### PR DESCRIPTION
**Pull request by jordanclark**
#898 @KamasamaK

### CODE REVIEW

**Comment by pfreitag** [comment]
@jordanclark I think this change should only be made on the param names, not the `syntax`, since `function` is a valid keyword there. Let me know what ya'll think.

**Comment by jordanclark** [comment]
Oh ya that makes sense, I'll fix

**Comment by jordanclark** [comment]
@pfreitag corrected, thanks for reviewing

**Comment by pfreitag** [comment]
You're welcome @jordanclark and thank you for the PR!

**Pull request merged**
