### PR TITLE
[ENHANCEMENT] By Engine

### LINKED ISSUE #583: By Engine
Should we add "functions and tags by engine" to navigation?

Then we would have something like "[Lucee > Unsupported Tags & Functions](http://docs.lucee.org/reference/unsupported.html)" "[Lucee > Additional Tags & Functions](http://docs.lucee.org/reference/additional.html)", but just the supported ones grouped by their engine.

* Adobe ColdFusion
    * an Adobe ColdFusion function/tag
    *  ...
* Lucee
    * an Lucee function/tag
    * ...
* All
    *  an function/tag which is supported by all engines
    *  ...

### PR DESCRIPTION
**Pull request by shaedrich**
Resolve #583

### CODE REVIEW

**Comment by shaedrich** [comment]
@pfreitag Could you share your opinion about [this](https://github.com/foundeo/cfdocs/issues/583#issuecomment-363761822) so I can go on?

**Comment by pfreitag** [comment]
Looks good - can you just verify that the code is all working properly and I'll merge it.

**Comment by shaedrich** [comment]
As mentioned in https://github.com/foundeo/cfdocs/issues/583#issuecomment-363761822 I'm unsure which would be the best solution for this.

**Comment by shaedrich** [comment]
@pfreitag It's tested now
image

**Comment by pfreitag** [comment]
Hi @shaedrich this is so old that it now has conflicts, I'm going to close this PR. I think adding so many items to the menu might be too much anyways - what do you think?

**Comment by shaedrich** [comment]
We could just take the first level. That might be helpful.

**Pull request closed without merging**
