### PR TITLE
Turn CFSqlType_Cheatsheet into a table

### PR DESCRIPTION
**Pull request by hawkrives**
I don't know if the website frontend can handle tables yet; do you need help with that?

### CODE REVIEW

**Comment by KamasamaK** [comment]
Based on how the [Date Time Cheatsheet](https://cfdocs.org/datetime) looks, it unfortunately does not support Markdown tables right now.

**Comment by hawkrives** [comment]
It looks like cfdocs uses https://github.com/rjeschke/txtmark.

Perhaps I will find the time to look into a replacement (maybe https://github.com/vsch/flexmark-java, which has … many options)

**Comment by KamasamaK** [comment]
OK. That's the same project @pfreitag proposed in #652 so sounds good.

**Comment by jmharrin** [comment]
I created a pull request yesterday to address this.  I replaced txtmark with an optimized build of flexmark so table markdown will be supported. #1361

**Comment by KamasamaK** [comment]
With #1477 merged, this can probably be revisited.

**Comment by pfreitag** [comment]
Thanks all!

**Pull request merged**
