### PR TITLE
Added result for ReplaceList

### PR DESCRIPTION
**Pull request by shaedrich**

### CODE REVIEW

**Comment by pfreitag** [comment]
Thank you this improves the example -- however I think it could be further improved by just making the entire example this:

`replaceList("My Test String", "Test,String", "Replaced,Sentence")`

Any chance you would like to update that as well?

**Comment by shaedrich** [comment]
That would make it much more clear. Additionally there would be no more unnecessary variables anymore.

**Comment by pfreitag** [comment]
Thanks FYI for future reference you can actually omit the `<cfoutput>` cfdocs will add that in automatically.

**Comment by shaedrich** [comment]
Okay, cool (Y) Thanks for that hint.

**Pull request merged**
