### PR TITLE
Add missing lucee tags and correct lucee doc links

### PR DESCRIPTION
**Pull request by jordanclark**
add missing lucee tags: cfpageencoding, cfforward, cfhtmlbody, cfstopwatch
change all docs.lucee.org links to https which is the canonical url

### CODE REVIEW

**Comment by shaedrich** [comment]
According to your overview of changes, they sound good. But putting them all in one pr makes it hard to check them.

**Comment by jordanclark** [comment]
@shaedrich sorry about that, as I've been committing more changes they've just been rolling into the same outstanding pull request. I can't create multiple pull requests unless I create a new branch for each commit. If you want to review them separately can't you just look at the changes in each commit?

**Comment by shaedrich** [comment]
Well, I'm not the one to decide that, but yeah, I highly suggest grouping related changes into the same branch so that you end up with separate pull requests for each specific change with can consist of one or a few more commits. Having 754 different files with different kind of changes — there's no easy way to check that anymore… It's a mess, sorry.

**Comment by jordanclark** [comment]
Okey dokey

**Pull request closed without merging**
