### PR TITLE
Guides not displaying

### PR DESCRIPTION
**Pull request by penhorwood**
The CGI guide was not displaying due to wrong name in the json.

The textbox guide was not displaying locally because that folder exist but the rewrite rule tried using /textbox as the path.  I renamed the textbox.md file to textbox-guide.md and everything works.

### CODE REVIEW

**Comment by penhorwood** [comment]
Is there a problem with this request?  The CGI guide is not working which is why I created this pull request.

**Comment by pfreitag** [comment]
Hi Andrew, the only thing I wasn't crazy about was renaming the testbox guide to testbox-guide... I think I would rather solve that problem in the rewrite rule.

**Comment by penhorwood** [comment]
Ok, I think the guide issues are fixed.  If you ever have an issue with any pull request please let me know so I can fix them.  Love the project.  Best docs for CF.

**Comment by pfreitag** [comment]
Thanks @penhorwood -- yes, sorry for not letting you know sooner why hesitated merging it at first.

**Pull request merged**
