### PR TITLE
ACF "struct" named param compatibility

### PR DESCRIPTION
**Pull request by jordanclark**
More #898 goodness

### CODE REVIEW

**Comment by pfreitag** [comment]
@jordanclark can you make the same changes as you did in #1152 here. Thanks

**Comment by pfreitag** [comment]
BTW - thanks for doing these in smaller PR chunks, it is easier for me to review lots of small PRs than one big one.

**Comment by jordanclark** [comment]
@pfreitag Will do. Doing separate PR & branches is good for me, helps with my git foo

**Comment by KamasamaK** [comment]
One thing to ensure in the future is that you're always branching from `master`. This was branched from `callback-params` that you used in #1152, which is why is contains a lot of the same changes from that. See [your network graph](https://github.com/jordanclark/cfdocs/network) to visualize this.

**Pull request closed without merging**
