### PR TITLE
Automatic creation of guide files

### PR DESCRIPTION
**Pull request by rscRoman**
Read and parse data.json to automatically create MarkDown files for following guides:
* ACF only
* Lucee only
* Deprecated
* Discouraged

### CODE REVIEW

**Comment by shaedrich** [comment]
I'm not sure if we would consider that guide. The closest thing we have I can think of, are listings.

**Comment by pfreitag** [comment]
@shaedrich I think these are ok in guides for now, since there is no way to add some of the additional metadata notes to listings.

**Comment by rscRoman** [comment]
@pfreitag This is my first Version of the automatic generation. Please give me any feedback if i should rebuild something.

**Comment by pfreitag** [comment]
Looks good to me, what do you think @shaedrich ?

**Comment by shaedrich** [comment]
Besides that, it looks good to me @pfreitag.

**Comment by pfreitag** [comment]
Ok, I'm going to merge it we can improve as needed - looks like handy info @rscRoman thanks for adding it!

**Comment by rscRoman** [comment]
I am happy that I can contribute to this great project.
If there is more that i can do, let me know.

**Comment by pfreitag** [comment]
One suggestion might be to use a `UL` instead of `h3` eg: `* functionName` instead of `### functionName` for each entry, I think it may render a bit cleaner that way.

**Comment by rscRoman** [comment]
Where should i put the "Minimum Version/Deprecated" info?
Looks a little lonely then.

**Comment by rscRoman** [comment]
Made a new Pull request #1280  with an upated view

**Pull request merged**
