### PR TITLE
Add StructEach Function

### PR DESCRIPTION
**Pull request by maryjos**

### CODE REVIEW

**Comment by pfreitag** [comment]
Good one - Thanks!

**Comment by pfreitag** [comment]
I saw you also updated the indexes thanks -- there is a utility that generates them (in utilities folder I think) so you don't have to do it manually when you add something new

**Comment by maryjos** [comment]
Ah okay, thanks, good to know!

**Comment by maryjos** [comment]
Oh I see it included my update to add the new Index page for Struct functions as well. Figured that should be in there since there was one for arrays.

**Comment by maryjos** [comment]
Boy, that leaderboard sure is slow to update though! Still haven't made it on (I would be contributing anyway, tired of waiting for Adobe to accept my help with docs, so will try to make these as good as possible!)

**Comment by maryjos** [comment]
Just noticed something too... you may want to add a secondary sort for number of lines for people tied on number of contributions. Lot of people with 1 contribution in there but seems to be random how they are ordered.

**Comment by maryjos** [comment]
I could of course do the change and check it in but I figure that's something the person in charge of the project should decide to do or not. ;-)

**Comment by pfreitag** [comment]
Yes for some reason you are not showing up on github under the contributors it usually happens after a few minutes. 

Feel free to update the sorting if u want

**Comment by maryjos** [comment]
Ah yeah I looked at what it returns, not easy to do that kind of sort. Probably not worth the trouble.

**Pull request merged**
