### PR TITLE
Add queryGetResult

### LINKED ISSUE #416: CF2016.0.3 Added queryGetResult
CF2016 Update 3 added a queryGetResult() function and related getResult() member function.  The functions returns a struct of query metadata (cached, executiontime, recordcount, sql).

### PR DESCRIPTION
**Pull request by cfvonner**
Closes #416

### CODE REVIEW

**Comment by cfvonner** [comment]
Fixing a couple of things and will resubmit.

**Comment by pfreitag** [comment]
Thanks @cfvonner BTW not sure if you knew this but you can run /utilities/indexer.cfm to automatically rebuild the indexes.

**Comment by cfvonner** [comment]
I didn't know about the indexer utility, but I'll use it next time.

Thanks,
Carl

------
Sent from my mobile device.

Carl Von Stetten
carl.vonstetten1@gmail.com
http://about.me/cfvonner

**Comment by pfreitag** [comment]
Cool - it only needs to be run if you add a new tag / function

**Pull request closed without merging**
