### PR TITLE
updated function category lists to add new functions to them

### PR DESCRIPTION
**Pull request by jcberquist**
This also resulted in the re-capitalizing of some functions to match the camel case capitalization cfdocs is using.

### CODE REVIEW

**Comment by jcberquist** [comment]
Ha, sorry, I am not thinking, I will submit this pull request after the other one is taken care of.

**Comment by pfreitag** [comment]
please resubmit, thanks

**Comment by jcberquist** [comment]
I should be able to just reopen this, correct?

**Comment by pfreitag** [comment]
looks like I can reopen too.

**Pull request merged**
