### PR TITLE
Initial commit: Added TryCF editor for code examples

### PR DESCRIPTION
**Pull request by abramadams**
This adds the TryCF editor/runner to doc.cfm.  To add an example to a doc page, just add a struct to the data json such as:
```javascript
"example": {
		"defaultEngine": "acf",
		"code": "<cfscript>
	originalArray = ['1','2','3'];
	writeDump( var=originalArray, label='Array' );

	convertedToList = arrayToList( originalArray );
	writeDump( var=convertedToList, label='List' );
</cfscript>"
	}
```

defaultEngine can be: `acf` for Adobe ColdFusion (version 10 at the moment) or `railo` for Railo 4.2 (versions will change as time goes on).

See doc: arraytolist for an example of the editor in use.

See issue #40 for initial request for this feature

### CODE REVIEW

**Comment by abramadams** [comment]
Latest commit also added Lucee 4.5 support to editor.

**Comment by pfreitag** [comment]
Closing this pull request, I merged parts of it manually. The main thing that I wanted to change was that instead of having the editor directly on the page, I wanted it to be invoked on demand (to keep page loads fast), so there is now a button "Run Code" next to the examples that brings up a bootstrap modal with the editor in it.

Thanks @abramadams so much for this work, couldn't have done it without this pull request!

**Comment by atuttle** [comment]
Great work so far guys. I think it may still need some more...

image

This is what I see at the bottom of the **Run Code** modal for [cfloop](http://cfdocs.org/cfloop). I disabled my ad blocker and still the buttons (between save gist and current engine) don't have icons. Clicking the second button doesn't seem to do anything. And is there intent to support engine switching? Right now it appears to be locked to ACF10.

Still... this is awesome. Thanks!

**Comment by pfreitag** [comment]
Correct switching the engine is broken, @abramadams - any ideas?

**Comment by abramadams** [comment]
Ah yes.  That part has changed a bit since I made my original PR. I'll see about merging the latest into cfdocs.

**Pull request closed without merging**
