### PR TITLE
Updated mime types for Excel

### PR DESCRIPTION
**Pull request by angel-chrystian**
For Excel there are more MIME types for the newest versions of Microsoft Office including the XLSX and open office formats.
Source: https://filext.com/faq/office_mime_types.html

### CODE REVIEW

**Comment by KamasamaK** [comment]
There are simply too many MIME types to list them all. Given the purpose of `values` (based on #489), perhaps they shouldn't even be enumerated there.

**Comment by pfreitag** [comment]
Yes, we shouldn't enumerate handy values in `values` it is for a finite list of options, we need another json key, maybe `suggestions` to list handy possible values which IDEs can use to provide autocomplete suggestions.

**Comment by KamasamaK** [comment]
@pfreitag Did you change your mind on this?

**Comment by pfreitag** [comment]
@KamasamaK nope, I merged it, and edited to add `suggestions` key.

**Pull request merged**
