### PR TITLE
Example: Create empty ordered struct using literal notation

### PR DESCRIPTION
**Pull request by shaedrich**

### CODE REVIEW

**Comment by shaedrich** [comment]
@pfreitag Travis failed for some reason. Can you run it again?
> The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .

**Comment by pfreitag** [comment]
sure @shaedrich - I restarted the build.

**Comment by pfreitag** [comment]
Ok - looks like travis is having trouble installing java8 at the moment, I'd assume they will fix this soon, if not we can try upgrading the build to java 11.

**Comment by shaedrich** [comment]
Okay :+1:

**Comment by pfreitag** [comment]
@shaedrich I have updated the travis.yml to use openjdk8 instead of oraclejdk8 that seams to fix the build error, but when I restart the build it just reuses the old travis.yml again, so I'll just merge this one -- looks ok to me.

**Pull request merged**
