### PR TITLE
Add description, related and param description

### PR DESCRIPTION
**Pull request by shaedrich**

### CODE REVIEW

**Comment by shaedrich** [comment]
> EXCEPTION in example 1: No matching Method/Function for call with named arguments found

`contactpath()` has no examples oO

**Comment by shaedrich** [comment]
@pfreitag Could you check what is going wrong with lucee job?

**Comment by pfreitag** [comment]
Yeah - I will look into that build error, I don't think it is necessarily from your pull it was failing before that.

**Comment by shaedrich** [comment]
Ah, okay. Thanks!

**Comment by pfreitag** [comment]
I have fixed the travis-ci test - this pull is still erroring with `threadjoin.json was NOT valid JSON`

**Comment by shaedrich** [comment]
Fixed

**Comment by pfreitag** [comment]
Thanks @shaedrich

**Comment by shaedrich** [comment]
You're welcome @pfreitag

**Pull request merged**
