### PR TITLE
[ENHANCEMENT] Make doc examples collapsible

### LINKED ISSUE #504: Better/more clear navigation on larger pages
On larger pages you have to scroll much to and fro. In my opinion this could be improved.
* Should there be a table of contents for longer pages?
* Should the sections be expandable/collapsable?
* Should there be tabs for cfml and cfscript syntax examples?

### PR DESCRIPTION
**Pull request by shaedrich**
Resolve #504

### CODE REVIEW

**Comment by shaedrich** [comment]
@pfreitag Is there something to quarrel with in this approach?

**Comment by pfreitag** [comment]
@shaedrich it looks good to me 

I just haven't had time to test this out (entire site will break if there is a bug so I usually test these types of changes first)... can you confirm that it works and I'll take your word if it is working and merge.

**Comment by shaedrich** [comment]
Unfortunately CommandBox does not work in my case. I can't figure out, why.

I did not change much. It's just wrapping these elements into collapsable bootstrap panels. So no big deal. Long story short: I'm 90 % sure.

**Comment by pfreitag** [comment]
@shaedrich would be great if you can get `box` running locally, are you on the CFML slack channel? If so post your issue in `#box-products` - I'm sure it can be resolved.

**Comment by shaedrich** [comment]
Okay, I tested it. One small adjustment but now it looks fine.

**Pull request merged**
