### PR TITLE
Add csrf functions

### PR DESCRIPTION
**Pull request by elpete**
Updated indexes as well.

### CODE REVIEW

**Comment by pfreitag** [comment]
Well this is a first, I just merged a pull from @ddspringle that also had the CSRF functions -- can you guys compare your work and see if there is anything in this pull that I should merge or should we just keep Denards version intact.

**Comment by ddspringle** [comment]
Great minds think alike! They look about the same... I didn't update the indexes except for security, so maybe grab the updated indexes from this one? My examples seem more relevant and I added additional text to the descriptions, etc to help identify what these are used for - but other than that, looks like we're all on the same page here ;)

**Comment by elpete** [comment]
Sounds good to me. 👍



Cheers,
Eric

**Comment by pfreitag** [comment]
Thanks guys, merged in the index changes.

**Pull request closed without merging**
